@startuml

class Player {
    -dx: int
    -dy: int
    -speed_y: int
    -jump: bool
    -is_grounded: bool
    -direction: int
    -counter: int
    -number: int
    -images_r: List[Surface]
    -images_l: List[Surface]
    -image: Surface
    -rect: Rect
    -width: int
    -height: int
    +restart(x: int, y: int): void
    +update(): int
    +collision_with_map(environment: Environment): bool
}

class Environment {
    -square_list: List[Tuple[Surface, Rect]]
    +__init__(): void
    +build_map(): void
    +draw(): void
}

class Water {
    -image: Surface
    -rect: Rect
    +__init__(x: int, y: int): void
}

class Coin {
    -image: Surface
    -rect: Rect
    +__init__(x: int, y: int): void
}

class Door {
    -image: Surface
    -rect: Rect
    +__init__(x: int, y: int): void
}

class Fish {
    -image: Surface
    -rect: Rect
    +__init__(x: int, y: int, number: int): void
}

class Button {
    -image: Surface
    -rect: Rect
    -clicked: bool
    +__init__(x: int, y: int, image: Surface): void
    +draw(): bool
}

Player "1" -- "1..*" Environment : uses >
Environment "1" -- "*" Water : contains >
Environment "1" -- "*" Coin : contains >
Environment "1" -- "*" Door : contains >
Environment "1" -- "*" Fish : contains >

@enduml
