@startuml

class User {
    +openApp()
    +selectMenuItem(menuItem: MenuItem)
    +navigateToSettings()
    +startGame()
    +viewStatistics()
}

class GameMenu {
    +displayMenu()
    +handleMenuItemSelection(item: MenuItem)
}

class Exit {
    +exitGame()
}

class StartGame {
    +loadLevel(levelName: String)
    +placeCoins()
    +displayCharacter(character: Character)
    +displayInfoBlock(infoBlock: InfoBlock)
}

class Statistics {
    +updatetStats(stats: Stats)
    +saveStats(stats: Stats)
    +displayStats(stats: Stats)
}

class CollectedCoins {
    +displayCoinsAmount(coins: Coins)
    +updateCoinAmount(newAmount: Int)
    +saveResult(result: Result)
}

class Coin {
    +displayCoins(coin: Coin)
    
}

class Player {
    +collectCoin(coin: Coin)
    +move(direction: Direction)
}

User -.-> GameMenu : uses >
User --->  Player : moves >
GameMenu o-- StartGame : starts >
GameMenu o-- Exit : uses >
GameMenu o-- Statistics : views >
CollectedCoins --> Player
Player --> Statistics


Coin <|-- Player
Coin ---> CollectedCoins

@enduml