@startuml

start

:Игровой процесс;
:Приложение отображает монеты;
:Пользователь может проходить уровень;
:По мере прохождения у пользователя есть возможность собирать монеты;
:Количество собранных монет приложение отображает в специальном блоке с информацией;
:После прохождения всех уровней приложение сохраняет результат, исходя из собранных монет;

stop

@enduml