@startuml

start

:Игровой процесс;
:Приложение отображает еду;
:Пользователь может проходить уровень;
:По мере прохождения у пользователя есть возможность собирать еду;
:Количество собранных единиц еды приложение добавляет к количеству жизней;
:Количество жизней персонажа отображается в специальном блоке с информацией;

stop

@enduml