@startuml
start

:Открытие меню;
while (Одна из кнопок нажата) is (Нет)
    :Ожидание;
endwhile

if (Нажата кнопка "START"?) then (Да)
  :Начало игрового процесса;
elseif (Нажата кнопка "STATISTICS"?) then (Да)
  :Открытие статистики предыдущих игр;
elseif (Нажата кнопка "EXIT"?) then (Да)
  :Выход из приложения;
endif

stop
@enduml