@startuml

start

:Персонаж в игре может быть перемещен с помощью клавиш WAD на клавиатуре;
:Нажатие клавиши W приводит к прыжку персонажа, клавиша A - движение влево, клавиша D - движение вправо; 
:При зажатии одной из клавиш A или D персонаж начинает двигаться в соответствующем направлении;
:Пользователь может управлять персонажем, изменяя его направление движения с помощью клавиатуры;
:На экране отображается анимация передвижения персонажа, при этом его позиция меняется в зависимости от выбранного направления движения; 
:Пользователь может следить за перемещением персонажа и управлять им для достижения цели в игре;

stop

@enduml