@startuml
actor Пользователь
participant Игра
participant Персонаж
participant Монета
participant Рыба
participant Препятствия
participant Счёт
participant Статистика

loop Игровой цикл
    Пользователь -> Игра: Запускает игру
    Пользователь -> Персонаж: Управляет персонажем
    Игра -> Персонаж: Начать движение
    Игра -> Монета: Генерировать монету
    Игра -> Рыба: Генерировать рыбу
    Игра -> Препятствия: Генерировать препятствия
    
    loop Пока не завершена игра
    Игра -> Персонаж: Обновить состояние
    Игра -> Монета: Проверить столкновения
    Игра -> Рыба: Проверить столкновения
    Игра -> Препятствия: Проверить столкновения
    Игра -> Пользователь: Отобразить игровое поле
    Монета -> Счёт: Прибавить к счёту
    end
    Счёт -> Статистика: Записать значение
    Игра -> Пользователь: Игра завершена
end
@enduml