@startuml
state "Статистика" as Statistics {
  [*] --> Отобразить_кнопки_для_выбора : Завершение игры
  state choice1 <<choice>>
  state choice2 <<choice>>
  Отобразить_кнопки_для_выбора --> choice1
  choice1 --> Нажата_кнопка_перезагрузки
  Нажата_кнопка_перезагрузки --> choice2: Существует ли файл statistics.csv?
  choice2 ---> Открыть_файл_в_режиме_дополнения : Файл существует
  choice2 --> Создать_файл :  Файл не существует
  Создать_файл --> Открыть_файл_в_режиме_дополнения
  Открыть_файл_в_режиме_дополнения --> Записать_данные
  Записать_данные : Дата, время, результат
  Записать_данные --> Закрыть_файл
  Закрыть_файл --> Перезапустить_игру
  choice1 --> Закрыть_приложение : Нажата кнопка выхода
}
@enduml
