@startuml
state "Движение персонажа" as Moving {
  [*] --> Поместить_персонажа_на_начальную_позицию
  Поместить_персонажа_на_начальную_позицию --> Пользователь_перемещает_персонажа
  state choice1 <<choice>>
  state choice2 <<choice>>
  Пользователь_перемещает_персонажа --> choice1 : Столкнулся с чем-либо?
  choice1 --> Столкновение : Да
  Столкновение --> choice2 : С чем?
  choice2 --> Столкновение_с_предметом 
  Столкновение_с_предметом --> Обновление_блока_с_информацией
  Обновление_блока_с_информацией : Количество монет и жизней
  choice2 --> Столкновение_с_препятствием 
  Столкновение_с_препятствием ---> Поместить_персонажа_на_начальную_позицию
  choice2 --> Столкновение_с_дверью
  Столкновение_с_дверью --> Прохождение_уровня
}
@enduml