@startuml
state "Демонстрация меню" as Menu {
  [*] --> Отобразить_меню : Запуск приложения
  state choice1 <<choice>>
  state choice2 <<choice>>
  Отобразить_меню --> choice1 : Нажата ли кнопка?
  choice1 --> Ожидание_нажатия : Нет
  Ожидание_нажатия --> choice1 : Нажата ли кнопка?
  choice1 ---> choice2 : Да
  choice2 --> Загрузка_игрового_уровня : Кнопка start
  Загрузка_игрового_уровня --> Отображение_препятствий
  Загрузка_игрового_уровня --> Отображение_предметов
  Загрузка_игрового_уровня --> Отображение_персонажа
  choice2 --> Сортировка_результатов : Кнопка statistics
  Сортировка_результатов : От большего к меньшему
  Сортировка_результатов --> Вывод_результатов
  choice2 --> Закрытие_приложения : Кнопка exit
}
@enduml
