@startuml
start

:Открытие меню;
while (одна из кнопок нажата) is (нет)
    :Ожидание;
endwhile

if (Это кнопка "START"?) then (да)
  :Построение уровня;
  :Размещение монет;
  :Отображение персонажа;
  :Начало игрового процесса;
elseif (Это кнопка "SETTINGS"?) then (да)
  :Открытие окна настроек;
elseif (Это кнопка "STATISTICS"?) then (да)
  :Открытие статистики предыдущих игр;
endif

stop
@enduml