@startuml
start

:Открытие меню;
while (одна из кнопок нажата) is (нет)
    :Ожидание;
endwhile

if (Нажата кнопка "START"?) then (да)
  :Начало игрового процесса;
elseif (Нажата кнопка "SETTINGS"?) then (да)
  :Открытие окна настроек;
elseif (Нажата кнопка "STATISTICS"?) then (да)
  :Открытие статистики предыдущих игр;
endif

stop
@enduml