@startuml

start

:Открытие меню;
  while (Кнопка "START" нажата?) is (нет)
    :Ожидание;
  endwhile

if (Да) then
:Приложение загружает игровой уровень;
:Приложение размещает монеты;
:Приложение отображает персонажа;
:Приложение отображает блок с информацией о персонаже;
:Пользователь может начинать игровой процесс;
endif

stop

@enduml